import type { Metadata } from "next"
import localFont from "next/font/local"
import { headers } from "next/headers"
import "./globals.css"
import "@nft-marketplace/ui/styles.css"
import "@rainbow-me/rainbowkit/styles.css"
import Providers from "./providers"

const geistSans = localFont({
  src: "./fonts/GeistVF.woff",
  variable: "--font-geist-sans",
})
const geistMono = localFont({
  src: "./fonts/GeistMonoVF.woff",
  variable: "--font-geist-mono",
})

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
}

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode
}>) {
  const cookie = headers().get("cookie")
  return (
    <html lang="en">
      <body className={`${geistSans.variable} ${geistMono.variable}`}>
        <Providers cookie={cookie}>{children}</Providers>
      </body>
    </html>
  )
}
